[package]
name = "semantic-engine-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
semantic-engine-core = { path = "../../crates/semantic-engine-core" }
serde_json.workspace = true
semantic-engine-package = { path = "../../crates/semantic-engine-package" }
semantic-engine-loopback = { path = "../../crates/semantic-engine-loopback" }
semantic-engine-protocol = { path = "../../crates/semantic-engine-protocol" }
semantic-engine-service = { path = "../../crates/semantic-engine-service" }
tokio.workspace = true
